# Generated by Django 4.2 on 2024-11-30 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=66, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Descriptions')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='gateways/img/%y%m%d%H%M', verbose_name='Avatar')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Price paid')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Void'), (10, 'Paid'), (20, 'Error'), (30, 'User Canceled'), (31, 'Refunded')], default=0, verbose_name='Status')),
                ('device_uuid', models.CharField(blank=True, max_length=66, null=True, verbose_name='Device UUID')),
                ('phone_number', models.CharField(max_length=11, validators=[utils.validators.PhoneNumberValidator()], verbose_name='Phone number')),
                ('consumed_code', models.PositiveIntegerField(verbose_name='Consumed reference code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.gateway')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
