# Generated by Django 4.2 on 2024-11-26 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists'}, help_text='Required. 66 characters or fewer. Letters, digits and underscore', max_length=66, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_\\.]+$', 'Enter a valid username starting with a-zthis value may contain only letters, numbers and underscore characters')], verbose_name='username'),
        ),
    ]
