# Generated by Django 4.2 on 2024-11-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'audio'), (1, 'video'), (2, 'audio')], default=2, verbose_name='File Type'),
        ),
    ]
