# Generated by Django 4.2 on 2024-11-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'pdf'), (1, 'video'), (2, 'audio')], default=2, verbose_name='File Type'),
        ),
    ]
